(function () {
  const pages = [
    {
      id: "signin",
      technicalName: "sign-in",
      menuLabel: "Sign In",
      path: "enterprise/sign-in.html",
      role: "public",
      section: "auth",
    },
    {
      id: "signup",
      technicalName: "sign-up",
      menuLabel: "Create Account",
      path: "enterprise/sign-up.html",
      role: "public",
      section: "auth",
    },
    {
      id: "operations_dashboard",
      technicalName: "operations-dashboard",
      menuLabel: "Operations Dashboard",
      path: "enterprise/operations-dashboard.html",
      role: "manager",
      section: "enterprise",
    },
    {
      id: "establishments_management",
      technicalName: "establishments-management",
      menuLabel: "Establishments",
      path: "enterprise/establishments-management.html",
      role: "manager",
      section: "enterprise",
    },
    {
      id: "queue_management",
      technicalName: "queue-management",
      menuLabel: "Queue Management",
      path: "enterprise/queue-management.html",
      role: "manager",
      section: "enterprise",
    },
    {
      id: "ticket_management",
      technicalName: "ticket-management",
      menuLabel: "Ticket Management",
      path: "enterprise/ticket-management.html",
      role: "manager",
      section: "enterprise",
    },
    {
      id: "analytics_dashboard",
      technicalName: "analytics-dashboard",
      menuLabel: "Analytics",
      path: "enterprise/analytics-dashboard.html",
      role: "manager",
      section: "enterprise",
    },
    {
      id: "queue_overview",
      technicalName: "queue-overview",
      menuLabel: "Queue Overview",
      path: "enterprise/queue-overview.html",
      role: "manager",
      section: "enterprise",
    },
    {
      id: "subscription_management",
      technicalName: "subscription-management",
      menuLabel: "Subscriptions",
      path: "enterprise/subscription-management.html",
      role: "manager",
      section: "enterprise",
    },
    {
      id: "queue_display",
      technicalName: "queue-display",
      menuLabel: "Queue Display",
      path: "queue-display.html",
      role: "display",
      section: "display",
    },
    {
      id: "queue_display_setup",
      technicalName: "queue-display-setup",
      menuLabel: "Display Setup",
      path: "queue-display-setup.html",
      role: "display",
      section: "display",
    },
    {
      id: "queue_display_control",
      technicalName: "queue-display-control",
      menuLabel: "Display Control",
      path: "queue-display-control.html",
      role: "display",
      section: "display",
    },
    {
      id: "ticket_kiosk",
      technicalName: "ticket-kiosk",
      menuLabel: "Ticket Kiosk",
      path: "client/ticket-kiosk.html",
      role: "public",
      section: "client",
    },
    {
      id: "waiting_board",
      technicalName: "waiting-board",
      menuLabel: "Waiting Board",
      path: "client/waiting-board.html",
      role: "public",
      section: "client",
    },
    {
      id: "pos_ticket",
      technicalName: "pos-ticket",
      menuLabel: "POS Ticket",
      path: "client/pos-ticket.html",
      role: "public",
      section: "client",
    },
    {
      id: "payment_pending",
      technicalName: "payment-pending",
      menuLabel: "Payment Pending",
      path: "client/payment-pending.html",
      role: "public",
      section: "client",
    },
    {
      id: "remote_tracking",
      technicalName: "remote-tracking",
      menuLabel: "Remote Tracking",
      path: "client/remote-tracking.html",
      role: "public",
      section: "client",
    },
    {
      id: "client_notifications",
      technicalName: "client-notifications",
      menuLabel: "Notifications",
      path: "client/client-notifications.html",
      role: "public",
      section: "client",
    },
  ];

  window.APP_PAGES = pages;
})();
