(function () {
  const pages = [
    {
      id: "signin",
      technicalName: "sign-in",
      menuLabel: "Sign In",
      path: "enterprise/sign-in.html",
      role: "public",
      allowedRoles: ["PUBLIC"],
      section: "auth",
    },
    {
      id: "signup",
      technicalName: "sign-up",
      menuLabel: "Create Account",
      path: "enterprise/sign-up.html",
      role: "public",
      allowedRoles: ["PUBLIC", "WAQTEK_TEAM"],
      section: "auth",
    },
    {
      id: "operations_dashboard",
      technicalName: "operations-dashboard",
      menuLabel: "Operations Dashboard",
      path: "enterprise/operations-dashboard.html",
      role: "manager",
      allowedRoles: ["ADMIN", "MANAGER", "WAQTEK_TEAM"],
      section: "enterprise",
    },
    {
      id: "admin_dashboard",
      technicalName: "admin-dashboard",
      menuLabel: "Admin Dashboard",
      path: "enterprise/admin-dashboard.html",
      role: "manager",
      allowedRoles: ["ADMIN"],
      section: "enterprise",
    },
    {
      id: "manager_dashboard",
      technicalName: "manager-dashboard",
      menuLabel: "Manager Dashboard",
      path: "enterprise/manager-dashboard.html",
      role: "manager",
      allowedRoles: ["MANAGER"],
      section: "enterprise",
    },
    {
      id: "establishments_management",
      technicalName: "establishments-management",
      menuLabel: "Establishments",
      path: "enterprise/establishments-management.html",
      role: "manager",
      allowedRoles: ["ADMIN", "WAQTEK_TEAM"],
      section: "enterprise",
    },
    {
      id: "queue_management",
      technicalName: "queue-management",
      menuLabel: "Queue Management",
      path: "enterprise/queue-overview.html",
      role: "manager",
      allowedRoles: ["ADMIN", "MANAGER"],
      section: "enterprise",
    },
    {
      id: "ticket_management",
      technicalName: "ticket-management",
      menuLabel: "Ticket Management",
      path: "enterprise/ticket-management.html",
      role: "manager",
      allowedRoles: ["ADMIN", "MANAGER"],
      section: "enterprise",
    },
    {
      id: "analytics_dashboard",
      technicalName: "analytics-dashboard",
      menuLabel: "Analytics",
      path: "enterprise/analytics-dashboard.html",
      role: "manager",
      allowedRoles: ["ADMIN", "WAQTEK_TEAM"],
      section: "enterprise",
    },
    {
      id: "queue_overview",
      technicalName: "queue-overview",
      menuLabel: "Queue Overview",
      path: "enterprise/queue-overview.html",
      role: "manager",
      allowedRoles: ["ADMIN", "MANAGER", "WAQTEK_TEAM"],
      section: "enterprise",
    },
    {
      id: "subscription_management",
      technicalName: "subscription-management",
      menuLabel: "Subscriptions",
      path: "enterprise/subscription-management.html",
      role: "manager",
      allowedRoles: ["ADMIN", "WAQTEK_TEAM"],
      section: "enterprise",
    },
    {
      id: "queue_display",
      technicalName: "queue-display",
      menuLabel: "Queue Display",
      path: "queue-display.html",
      role: "display",
      allowedRoles: ["ADMIN", "MANAGER"],
      section: "display",
    },
    {
      id: "queue_display_setup",
      technicalName: "queue-display-setup",
      menuLabel: "Display Setup",
      path: "queue-display-setup.html",
      role: "display",
      allowedRoles: ["ADMIN", "MANAGER"],
      section: "display",
    },
    {
      id: "queue_display_control",
      technicalName: "queue-display-control",
      menuLabel: "Display Control",
      path: "queue-display-control.html",
      role: "display",
      allowedRoles: ["ADMIN", "MANAGER"],
      section: "display",
    },
    {
      id: "pos_ticket",
      technicalName: "pos-ticket",
      menuLabel: "POS Ticket",
      path: "client/pos-ticket.html",
      role: "public",
      allowedRoles: ["ADMIN", "MANAGER"],
      section: "client",
    },
    {
      id: "take_ticket",
      technicalName: "take-ticket",
      menuLabel: "Prendre un ticket",
      path: "client/take-ticket.html",
      role: "public",
      allowedRoles: ["ADMIN", "MANAGER"],
      section: "client",
    },
    {
      id: "payment_pending",
      technicalName: "payment-pending",
      menuLabel: "Payment Pending",
      path: "client/payment-pending.html",
      role: "public",
      allowedRoles: ["PUBLIC"],
      section: "client",
    },
    {
      id: "remote_tracking",
      technicalName: "remote-tracking",
      menuLabel: "Remote Tracking",
      path: "client/remote-tracking.html",
      role: "public",
      allowedRoles: ["PUBLIC"],
      section: "client",
    },
  ];

  window.APP_PAGES = pages;
})();
